#!/bin/sh
#
# BSD 3-Clause License
# 
# Copyright (c) 2018 GitHub.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e
ROOTDIR=$(dirname $0)/..
cd $ROOTDIR

. packaging/version.sh

make clean
make -C cli clean

make
make -C cli

./cli/glb-director-cli build-config packaging/forwarding_table.json packaging/forwarding_table.bin

fpm -f -s dir -t deb \
	-n glb-director \
	-v ${GLB_DIRECTOR_VERSION} \
	-d 'dpdk > 17.11' \
    -d 'libjansson4' \
	--deb-systemd packaging/glb-director.service \
	--config-files /etc \
	build/app/glb-director=/usr/sbin/ \
	cli/glb-director-cli=/usr/sbin/ \
	cli/glb-config-check=/usr/sbin/ \
	packaging/director.conf=/etc/glb/ \
	packaging/forwarding_table.bin=/etc/glb/ \
	packaging/glb-director=/etc/default/

if [ -d "$BUILDDIR" ]; then
  cp glb-director_${GLB_DIRECTOR_VERSION}_amd64.deb $BUILDDIR/
fi

make clean
make -C cli clean
