#!/bin/sh
set -e
ROOTDIR=$(dirname $0)/..
cd $ROOTDIR

. packaging/version.sh

make clean
make -C cli clean

make
make -C cli

./cli/glb-director-cli build-config packaging/forwarding_table.json packaging/forwarding_table.bin

fpm -f -s dir -t deb \
	-n glb-director \
	-v ${GLB_DIRECTOR_VERSION} \
	-d 'dpdk > 17.11' \
    -d 'libjansson4' \
	--deb-systemd packaging/glb-director.service \
	--config-files /etc \
	build/app/glb-director=/usr/sbin/ \
	cli/glb-director-cli=/usr/sbin/ \
	cli/glb-config-check=/usr/sbin/ \
	packaging/director.conf=/etc/glb/ \
	packaging/forwarding_table.bin=/etc/glb/ \
	packaging/glb-director=/etc/default/

if [ -d "$BUILDDIR" ]; then
  cp glb-director_${GLB_DIRECTOR_VERSION}_amd64.deb $BUILDDIR/
fi

make clean
make -C cli clean
