#!/bin/bash

set -e

HOSTPATH=$(cd $(dirname "$0") && cd .. && pwd)
cd "$(dirname "$0")/.."

. script/helpers/folding.sh

begin_fold "Preparing Docker build environment"
(
  # Container for glb-healthcheck
  docker build -t glb-healthcheck -f script/Dockerfile.latest script

  # Container for glb-director and glb-redirect
  docker build -t glb-director-redirect -f script/Dockerfile.stretch script

)
end_fold

begin_fold "Building packages"
(
  # prep
  rm -rf tmp/build/
  mkdir -p tmp/build/

  docker run --rm \
    --volume "$HOSTPATH":/glb \
    "glb-healthcheck" \
    bash -c "cd /glb/src/glb-healthcheck && \
		make BUILDDIR=/glb/tmp/build clean mkdeb"

  docker run --rm \
    --volume "$HOSTPATH":/glb \
    "glb-director-redirect" \
    bash -c "cd /glb/tmp/build && \
		 /glb/src/glb-director/script/cibuild /glb/tmp/build  && \
		 cd /glb/src/glb-redirect && \
		 make BUILDDIR=/glb/tmp/build clean mkdeb"

)
end_fold