FROM debian:jessie

RUN echo 'deb http://ftp.debian.org/debian jessie-backports main' >>/etc/apt/sources.list
RUN apt-get update && apt-get -y install curl

# DPDK 
RUN curl -s https://packagecloud.io/install/repositories/github/unofficial-dpdk-stable/script.deb.sh | bash
RUN apt-get update && apt-get install -y build-essential dpdk dpdk-dev wget pkg-config libjansson-dev libjansson-dbg

# iptables / DKMS
RUN apt-get update && apt-get install -y iptables-dev dkms debhelper
