#!/bin/bash

set -e

HOSTPATH=$(cd $(dirname "$0") && cd .. && pwd)
cd "$(dirname "$0")/.."

. script/helpers/folding.sh

begin_fold "Testing glb-healthcheck daemon"
(
  vagrant ssh director-test -- bash /dev/stdin <<'EOF'
    cd /vagrant/src/glb-healthcheck
    sudo script/test
EOF
)
