#!/bin/bash

set -e

HOSTPATH=$(cd $(dirname "$0") && cd .. && pwd)
cd "$(dirname "$0")/.."

. script/helpers/folding.sh

begin_fold "Testing glb-healthcheck daemon"
(
  vagrant ssh director-test -- sudo bash /dev/stdin <<'EOF'
    . /etc/profile.d/gopath.sh
    cd /vagrant/src/glb-healthcheck
    script/test
EOF
)
end_fold
