#!/bin/bash

set -e

HOSTPATH=$(cd $(dirname "$0") && cd .. && pwd)
cd "$(dirname "$0")/.."

. script/helpers/folding.sh

begin_fold "Testing GLB-REDIRECT iptables module"
(
  vagrant ssh director -- bash /dev/stdin <<'EOF'
    cd /vagrant/src/glb-redirect
    sudo script/test
EOF
)
end_fold
