#!/bin/sh
#
# BSD 3-Clause License
# 
# Copyright (c) 2020 GitHub.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e
ROOTDIR=$(dirname $0)/..
cd $ROOTDIR

. packaging/version.sh

make -C ../glb-director/cli
make

../glb-director/cli/glb-director-cli build-config ../glb-director/packaging/forwarding_table.json ../glb-director/packaging/forwarding_table.bin

fpm -f -s dir -t deb \
	-n glb-director-xdp \
	-v ${GLB_DIRECTOR_XDP_VERSION} \
	-d "xdp-root-shim" \
	-d "libbpf4.19" \
    -d "glb-director-cli = ${GLB_DIRECTOR_VERSION}" \
	--conflicts 'glb-director' \
    --license 'BSD 3-Clause' \
    --maintainer 'GitHub <opensource+glb-director@github.com>' \
	--deb-systemd packaging/glb-director-xdp.service \
	--after-upgrade packaging/after-upgrade-custom-systemd.sh \
	--after-install packaging/after-upgrade-custom-systemd.sh \
	--config-files /etc \
	glb-director-xdp=/usr/sbin/ \
	bpf/glb_encap.o=/usr/share/glb-director-xdp/ \
	bpf/glb_encap_trace.o=/usr/share/glb-director-xdp/ \
	../glb-director/packaging/director.conf=/etc/glb/ \
	../glb-director/packaging/forwarding_table.bin=/etc/glb/ \
	packaging/glb-director-xdp=/etc/default/

fpm -f -s dir -t deb \
	-n xdp-root-shim \
	-v ${XDP_ROOT_SHIM_VERSION} \
	-d "libbpf4.19" \
	--license 'BSD 3-Clause' \
    --maintainer 'GitHub <opensource+glb-director@github.com>' \
	--deb-systemd packaging/xdp-root-shim\@.service \
	--after-upgrade packaging/after-upgrade-custom-systemd.sh \
	--after-install packaging/after-upgrade-custom-systemd.sh \
	--config-files /etc \
	xdp-root-shim/xdp-root-shim=/usr/sbin/ \
    bpf/tailcall.o=/usr/share/xdp-root-shim/ \
    packaging/xdp-root-shim=/etc/default/

if [ -d "$BUILDDIR" ]; then
  cp glb-director-xdp_${GLB_DIRECTOR_XDP_VERSION}_amd64.deb $BUILDDIR/
  cp xdp-root-shim_${XDP_ROOT_SHIM_VERSION}_amd64.deb $BUILDDIR/
fi

make clean
