#!/bin/bash
#
# BSD 3-Clause License
# 
# Copyright (c) 2018 GitHub.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
# 
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
# 
# * Neither the name of the copyright holder nor the names of its
#   contributors may be used to endorse or promote products derived from
#   this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

export BASEDIR=$(cd $(dirname "$0") && cd .. && pwd)
cd "$(dirname "$0")/.."

export GOPATH=/go
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

. ../../script/helpers/folding.sh

# Ensure BPF filesystem is mounted (needed for XDP map pinning)
if ! mount | grep -q 'type bpf'; then
  mount -t bpf bpf /sys/fs/bpf || true
fi

# If kernel headers for the running kernel aren't available, find what we have
if [ ! -d "/usr/src/linux-headers-$(uname -r)" ]; then
  AVAILABLE_HEADERS=$(ls -d /usr/src/linux-headers-*-generic 2>/dev/null | head -1 || true)
  if [ -n "$AVAILABLE_HEADERS" ]; then
    # Extract the version from the available headers path
    AVAILABLE_KVER=$(basename "$AVAILABLE_HEADERS")
    AVAILABLE_KVER="${AVAILABLE_KVER#linux-headers-}"
    export KVER="$AVAILABLE_KVER"
    echo "Using kernel headers version: $KVER"
  fi
fi

begin_fold "Building glb-director-xdp for testing"
(
  make -j4 -C ../glb-director/cli
  make clean
  rm -f xdp-root-shim/xdp-root-shim
  make # scan-build bricks go
)
end_fold

begin_fold "Running scapy packet tests against glb-director XDP"
(
  GLB_DIRECTOR_TYPE="xdp" PYTHONPATH=$(pwd)/../scapy-glb-gue/:$PYTHONPATH nosetests -v -w ../glb-director -a '!director_type' -a 'director_type=xdp'
)
end_fold
