#!/bin/sh
set -e
ROOTDIR=$(dirname $0)/..
cd $ROOTDIR

. packaging/version.sh

rm -rf .gopath
mkdir -p .gopath/src/github.com/github
ln -s `pwd`/../../ .gopath/src/github.com/github/glb-director
export GOPATH=`pwd`/.gopath
cd $GOPATH/src/github.com/github/glb-director/src/glb-healthcheck
go build

fpm -f -s dir -t deb \
	-n glb-healthcheck \
	-v ${GLB_HEALTHCHECK_VERSION} \
	--deb-systemd packaging/glb-healthcheck.service \
	--config-files /etc/glb \
	glb-healthcheck=/usr/sbin/ \
	packaging/healthcheck.conf=/etc/glb/ \
	packaging/forwarding_table.src.json=/etc/glb/ \
	packaging/forwarding_table.checked.json=/etc/glb/

if [ -d "$BUILDDIR" ]; then
  cp glb-healthcheck_${GLB_HEALTHCHECK_VERSION}_amd64.deb $BUILDDIR/
fi
