#!/bin/sh
set -e
ROOTDIR=$(dirname $0)/..
cd $ROOTDIR

rm -rf .gopath
mkdir -p .gopath/src/github.com/github
ln -s `pwd`/../../ .gopath/src/github.com/github/glb-director
export GOPATH=`pwd`/.gopath
cd $GOPATH/src/github.com/github/glb-director/src/glb-healthcheck
go build
