#!/bin/bash -e

set -e
ROOTDIR=$(dirname $0)/..
cd $ROOTDIR

rm -rf .gopath
mkdir -p .gopath/src/github.com/github
ln -s `pwd`/../../ .gopath/src/github.com/github/glb-director
export GOPATH=`pwd`/.gopath
cd $GOPATH/src/github.com/github/glb-director/src/glb-healthcheck

echo 'Building...'
go build

date "+%Y-%m-%dT%H:%M:%SZ"
echo "Beginning tests"
echo "=== GO TEST ==="

go test -v

echo "=== SHELL TEST ==="

ls -1 test/test-*.sh | xargs -I % -n 1 /bin/bash %

echo "==="
date "+%Y-%m-%dT%H:%M:%SZ"
echo "Done."
