name: ci

on: [push]

permissions:
  contents: read

jobs:
  package-build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro: [focal, noble]
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Run package build ${{ matrix.distro }}
      run: script/cibuild-create-packages ${{ matrix.distro }}
    - name: Tar files
      run: tar -cvf glb-director-${{ matrix.distro }}.tar $GITHUB_WORKSPACE/tmp/build
    - name: Upload Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: glb-director-${{ matrix.distro }}
        path: glb-director-${{ matrix.distro }}.tar
